pipeline
{
    agent
	{
        dockerfile
		{
        filename 'Dockerfile'
        dir 'utilities'
        }
    }
    stages
	{
        stage('Checkout')
		{
            steps
			{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/adityakakade21/backend-automation.git']])
            }
		}
        stage('log version info')
		{
            steps
			{
                sh 'python --version'
            }
		}
        stage('Test')
		{
            steps
			{
                git 'https://github.com/adityakakade21/backend-automation.git'
                sh 'behave'
            }
        }
		stage('Report')
		{
            steps
			{
                sh 'behave  --no-capture -f allure_behave.formatter:AllureFormatter -o AllureRepoers'
            }
        }
    }
	post
		{
		    always {
			         archiveArtifacts artifacts: 'AllureRepoers/', followSymlinks: false

                  }

        }
}